import { NgModule } from '@angular/core';
import {
  CategoryInfoServiceProxy,
  CategoryServiceProxy,
  CurrentUserServiceProxy,
  FileServiceProxy,
  HrCompanyInfoServiceProxy,
  HrCompanyServiceProxy,
  InterestServiceProxy,
  JobApplicationInfoServiceProxy,
  JobApplicationServiceProxy,
  JobFieldServiceProxy,
  JobPostFieldInfoServiceProxy,
  JobPostFieldServiceProxy,
  JobPostInfoServiceProxy,
  JobPostServiceProxy,
  MenuInfoServiceProxy,
  PostServiceProxy,
  RegistrationServiceProxy,
  SettingInfoServiceProxy,
  TenantServiceProxy,
  TokenAuthServiceProxy,
  UserCVServiceProxy,
  UserJobSettingInfoServiceProxy,
  UserJobSettingServiceProxy,
  UserProfileInfoServiceProxy,
  UserProfileServiceProxy,
} from './sys-service-proxies';

@NgModule({
  declarations: [],
  imports: [],
  providers: [
    //api sys
    MenuInfoServiceProxy,
    SettingInfoServiceProxy,
    CurrentUserServiceProxy,
    TokenAuthServiceProxy,
    TenantServiceProxy,
    CategoryInfoServiceProxy,
    CategoryServiceProxy,
    JobFieldServiceProxy,
    PostServiceProxy,
    JobPostFieldServiceProxy,
    JobPostServiceProxy,
    JobPostInfoServiceProxy,
    JobApplicationInfoServiceProxy,
    JobApplicationServiceProxy,
    JobPostFieldInfoServiceProxy,
    UserCVServiceProxy,
    FileServiceProxy,
    UserProfileInfoServiceProxy,
    UserProfileServiceProxy,
    UserJobSettingInfoServiceProxy,
    UserJobSettingServiceProxy,
    InterestServiceProxy,
    HrCompanyInfoServiceProxy,
    HrCompanyServiceProxy,
    RegistrationServiceProxy
  ],
})
export class ServiceProxiesModule {}
